# Generated by Django 4.2.6 on 2023-10-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(to='list.genres'),
        ),
    ]
